services:
  db:
    container_name: postgres
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
